const SKILLS = [
  {id:'S1', area:'Structure', title:'Build a Complete Sentence', short:'Complete sentences', outcome:'Can I identify and build a complete basic English sentence?', next:'S2', description:'A complete basic sentence has a subject and a verb, in a clear order.'},
  {id:'S2', area:'Structure', title:'Subject–Verb Agreement', short:'Subject–verb agreement', outcome:'Can I choose a verb that agrees with the subject?', next:'S3', description:'Singular and plural subjects need matching verb forms.'},
  {id:'S3', area:'Structure', title:'Basic Verb Forms', short:'Basic verb forms', outcome:'Can I use basic present, past, and continuous verb forms appropriately?', next:'S4', description:'Verb forms show when an action happens.'},
  {id:'S4', area:'Structure', title:'Recognize Word Classes', short:'Word classes', outcome:'Can I identify how a word functions in a sentence?', next:'V1', description:'Words can work as nouns, verbs, adjectives, and more.'},
  {id:'V1', area:'Vocabulary', title:'Build Word Families', short:'Word families', outcome:'Can I recognize and use related forms of a word?', next:'V2', description:'Related words can change form and function.'},
  {id:'V2', area:'Vocabulary', title:'Understand Vocabulary in Context', short:'Vocabulary in context', outcome:'Can I work out the meaning of an unfamiliar word from context?', next:'R1', description:'Context gives useful clues about new words.'},
  {id:'R1', area:'Reading', title:'Find the Main Idea', short:'Main idea', outcome:'Can I identify what a paragraph is mainly about?', next:'R2', description:'The main idea is the central point of a paragraph.'},
  {id:'R2', area:'Reading', title:'Identify Supporting Details', short:'Supporting details', outcome:'Can I distinguish the main point from information that supports it?', next:'C1', description:'Details explain, prove, or illustrate the main idea.'},
  {id:'C1', area:'Composition', title:'Write a Topic Sentence', short:'Topic sentences', outcome:'Can I write a clear sentence that expresses the main idea of a paragraph?', next:'C2', description:'A topic sentence introduces a clear, focused paragraph idea.'},
  {id:'C2', area:'Composition', title:'Develop Supporting Ideas', short:'Supporting ideas', outcome:'Can I add relevant information that explains or supports my main idea?', next:null, description:'Supporting ideas make a paragraph clear and convincing.'}
];
const DIAGNOSTIC = [
 ['S1','Which is a complete sentence?',['Because the students were tired.','The students in the classroom.','The students were tired.','After the long lecture.'],2,'A complete sentence needs a subject and a verb. “The students were tired” has both.'],
 ['S1','Choose the correct sentence.',['Every morning to university Sara goes.','Sara goes to university every morning.','Sara every morning university goes.','Goes Sara every morning to university.'],1,'In a basic English sentence, the subject normally comes before the verb.'],
 ['S2','Choose the correct verb: The students ___ English every day.',['studies','study','studying','studied'],1,'“Students” is plural, so we use the base verb “study.”'],
 ['S2','Choose the correct sentence.',['My friend like coffee.','My friend likes coffee.','My friend liking coffee.','My friend like coffees.'],1,'“My friend” is singular, so the present-simple verb is “likes.”'],
 ['S3','Yesterday, we ___ a short quiz.',['take','takes','took','are taking'],2,'“Yesterday” signals the past; the past form of take is “took.”'],
 ['S3','Look! The lecturer ___.',['speaks','spoke','is speaking','speak'],2,'“Look!” shows an action happening now, so use “is speaking.”'],
 ['S4','In “They study carefully,” carefully is a:',['noun','verb','adjective','adverb'],3,'“Carefully” tells us how they study, so it is an adverb.'],
 ['S4','In “The explanation was clear,” clear is a:',['noun','verb','adjective','pronoun'],2,'“Clear” describes the explanation, so it is an adjective.'],
 ['V1','Choose the correct form: Her ___ was very clear.',['explain','explains','explanation','explaining'],2,'A noun is needed after “Her.” “Explanation” is the noun form.'],
 ['V1','Which word belongs to the same family as “success”?',['successful','succeeding','successfully','All of these'],3,'Success, successful, succeed, and successfully are related word-family forms.'],
 ['V2','The path was narrow, so only one person could walk on it at a time. “Narrow” means:',['wide','not wide','dangerous','long'],1,'The clue “only one person” tells us that narrow means not wide.'],
 ['V2','The room was silent; nobody was speaking. “Silent” means:',['very noisy','quiet','crowded','bright'],1,'“Nobody was speaking” is the context clue for quiet.'],
 ['V2','Although the task was difficult, Lina was determined to finish it. “Determined” most nearly means:',['not interested','decided firmly','confused','tired'],1,'The phrase “to finish it” shows that Lina had made a firm decision.'],
 ['R1','What is the main idea? “Many students use planners to organize deadlines, classes, and study time. A planner can help them feel more prepared.”',['Planners are expensive.','Planners help students organize their work.','Classes are always difficult.','Students dislike deadlines.'],1,'Both sentences focus on how planners help students organize work.'],
 ['R1','Choose the best main idea: “Sleep helps the brain remember new information. It can also improve concentration in class.”',['Sleep supports learning.','Classes start early.','Students need phones.','Memory is difficult.'],0,'Both details support the broader idea that sleep helps learning.'],
 ['R1','A paragraph gives examples of campus clubs, sports, and volunteering. Its main idea is most likely:',['Ways students can get involved on campus.','How to pass exams.','Why sports are expensive.','How to find a classroom.'],0,'All the examples are ways of participating in campus life.'],
 ['R2','Which is a supporting detail for “Regular reading builds vocabulary”?',['Reading is a useful habit.','Readers meet new words in different contexts.','Vocabulary is important.','Students have many courses.'],1,'This detail explains how regular reading can build vocabulary.'],
 ['R2','In a paragraph about exercise, which sentence is a supporting detail?',['Exercise has several benefits for students.','For example, a short walk can reduce stress after studying.','Students have busy lives.','Health is important.'],1,'“For example” introduces a specific detail supporting the main point.'],
 ['R2','Which detail best supports “Group study can be effective”?',['Students study many subjects.','Explaining an idea to a classmate can deepen understanding.','Libraries have chairs.','Some students prefer mornings.'],1,'It gives a reason group study can work.'],
 ['C1','Which is the strongest topic sentence?',['My city has many things.','There are several reasons why campus libraries are valuable study spaces.','Libraries.','I went to the library yesterday with my friend.'],1,'It clearly introduces one focused paragraph topic.'],
 ['C1','Choose the best topic sentence for a paragraph about time management.',['Time is a thing.','Students should manage their time carefully to meet academic responsibilities.','My friend uses a clock.','There are 24 hours in a day.'],1,'It states a focused main point that can be developed.'],
 ['C1','A topic sentence should usually:',['introduce the main point','give every detail','ask many unrelated questions','end the paragraph'],0,'A topic sentence tells the reader what the paragraph will be about.'],
 ['C2','Which sentence best supports “Online course materials can help students review”?',['Students use the internet.','They allow students to revisit a lecture or reading when needed.','Courses are important.','Some students have laptops.'],1,'It directly explains how the materials support review.'],
 ['C2','Choose the best supporting idea for “Learning vocabulary in context is useful.”',['Words are everywhere.','A sentence can show how a new word is used and what it may mean.','Vocabulary has letters.','Students enjoy different activities.'],1,'It explains why context is useful for learning a new word.']
].map(([skillId,question,options,correct,explanation],i)=>({id:`D${i+1}`,skillId,question,options,correct,explanation}));
const S1 = {quick:[DIAGNOSTIC[0],DIAGNOSTIC[1]], practice:[
 {question:'Which sentence is complete?',options:['The students in the library.','After the class finished.','The students are in the library.','Because the library is quiet.'],correct:2,explanation:'The sentence needs a subject and a verb. “The students are” gives both.'},
 {question:'Choose the best order.',options:['English study students every day.','Students study English every day.','Study students English every day.','Every day English students study.'],correct:1,explanation:'A clear basic order is subject + verb + object + time.'},
 {question:'Which correction makes this complete? “My classmates very helpful.”',options:['My classmates are very helpful.','My classmates very are helpful.','Are my classmates helpful very.','My classmates helpful.'],correct:0,explanation:'“Are” is the missing verb. It connects the subject to its description.'}
], mastery:[
 {question:'Which is a complete sentence?',options:['When the exam ended.','The exam ended at noon.','After the difficult exam.','The students in room 12.'],correct:1,explanation:'“The exam ended at noon” includes a subject and a verb.'},
 {question:'Choose the correct order.',options:['The team presents its project tomorrow.','Tomorrow its project presents the team.','Presents the team tomorrow its project.','Its project the team presents tomorrow.'],correct:0,explanation:'English normally uses subject + verb + object.'},
 {question:'What is missing? “The teacher at her desk.”',options:['A subject','A verb','An adjective','A time word'],correct:1,explanation:'“The teacher” is the subject; the sentence needs a verb such as “is.”'}
]};
const COPY = {ar:{'Foundation Check':'فحص الأساس','Learn & Practise':'تعلّم وتدرّب','My Foundation':'أساسي اللغوي',"I'm Stuck":'أحتاج إلى مساعدة','Start Foundation Check':'ابدأ فحص الأساس','Continue':'متابعة','Check My Answer':'تحقق من إجابتي','Try Again':'حاول مرة أخرى','Back to My Foundation':'العودة إلى أساسي اللغوي','Quick Fix':'حل سريع','Find Your Foundation Gaps':'اكتشف فجواتك الأساسية','Your Foundation Profile':'ملفك الأساسي','Your Recommended Path':'مسارك المقترح','Ready':'جاهز','Developing':'قيد التطوير','Needs Practice':'يحتاج إلى تدريب','Practise This Skill':'تدرّب على هذه المهارة'}};
